### ISSUE TITLE
convertAsync fails if the filename to be converted contain spaces.

### ISSUE THREAD

**Issue by kartik1998** [kartik1998/pdf-images#15]

**Comment by FlorinProfeanuVEGO** [comment]
Hi, can you estimate when you can fix this issue?

**Comment by kartik1998** [comment]
Hi @FlorinProfeanuVEGO , i've merged the patch. Will update in this thread when it's deployed.

**Comment by kartik1998** [comment]
Hi, the patch 1.3.1 has been deployed.
